# Generated by Django 5.0.6 on 2024-08-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', help_text='The description of the product (optional).', verbose_name='Description'),
        ),
    ]
