# Use an official Python runtime as the base image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Set unbuffered output for python
# 1. Prevents Python from writing pyc files to disc
# 2. Prevents Python from buffering stdout and stderr
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Poetry's configuration:
ENV POETRY_VIRTUALENVS_CREATE=false

# Install dependencies
RUN apt-get update \
    && apt-get install -y netcat-traditional \
    && apt-get install make \
    && pip install --upgrade pip \
    && pip install poetry

# Copy the entrypoint.sh file into the container and make it executable
COPY /scripts/entrypoint.sh .
RUN chmod +x entrypoint.sh

# Copy Makefile
COPY ./Makefile .

# Copy poetry.lock and pyproject.toml
COPY ./pyproject.toml .
COPY ./poetry.lock .

# Install project dependencies
RUN make install-dev

# Run entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
