# Generated by Django 5.1.6 on 2025-05-07 14:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last updated.', verbose_name='Updated at')),
                ('bank', models.CharField(help_text='The bank code associated with the account.', max_length=10)),
                ('agency', models.CharField(help_text='The agency number associated with the account.', max_length=10)),
                ('account_number', models.CharField(help_text='The account number associated with the account.', max_length=20)),
                ('user', models.ForeignKey(help_text='The User associated with the account.', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
    ]
