# Generated by Django 5.1.6 on 2025-04-26 03:09

import core.shared.field_validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last updated.', verbose_name='Updated at')),
                ('name', models.CharField(help_text='The name of the asset.', max_length=255, verbose_name='Name')),
                ('symbol', models.CharField(help_text='The symbol of the product', max_length=10, verbose_name='Symbol')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the asset. Must be greater than or equal to 0.', max_digits=10, validators=[core.shared.field_validators.NonNegativeValueValidator()], verbose_name='Price')),
                ('image_url', models.URLField(help_text='The image url of the asset.', verbose_name='Image URL')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='AssetDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last updated.', verbose_name='Updated at')),
                ('datetime', models.DateTimeField(help_text='The datetime of the asset-daily.', verbose_name='Date')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the asset in that given time. Must be greater than or equal to 0.', max_digits=10, validators=[core.shared.field_validators.NonNegativeValueValidator()], verbose_name='Price')),
                ('asset', models.ForeignKey(help_text='The asset related to the asset-daily.', on_delete=django.db.models.deletion.CASCADE, related_name='asset_dailies', to='homebroker.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Asset Daily',
                'verbose_name_plural': 'Assets Dailies',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last updated.', verbose_name='Updated at')),
                ('name', models.CharField(help_text='The name of the wallet.', max_length=255, verbose_name='Name')),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The total that the user invested in that wallet. Must be greater than 0.0.', max_digits=10, validators=[core.shared.field_validators.NonNegativeValueValidator()], verbose_name='Total Invested')),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The current balance of the wallet. Must be greater than or equal to 0.0.', max_digits=10, validators=[core.shared.field_validators.NonNegativeValueValidator()], verbose_name='Current Balance')),
                ('user', models.ForeignKey(help_text='The user who created the wallet.', on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last updated.', verbose_name='Updated at')),
                ('shares', models.IntegerField(help_text='The number of shares related to the order.', verbose_name='Shares')),
                ('partial', models.IntegerField(default=0, help_text='The number of shares already bought.', verbose_name='Partial')),
                ('share_price', models.DecimalField(decimal_places=2, help_text='The price of a single share.', max_digits=10, verbose_name='Share price')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='The total price of the order.', max_digits=10, verbose_name='Price')),
                ('status', models.CharField(choices=[('CLOSED', 'Closed'), ('FAILED', 'Failed'), ('OPEN', 'Open')], default='OPEN', help_text='The status of the order.', max_length=10, verbose_name='Status')),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], help_text='The type of the order.', max_length=10, verbose_name='Type')),
                ('asset', models.ForeignKey(help_text='The asset related to the order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='homebroker.asset', verbose_name='Asset')),
                ('user', models.ForeignKey(help_text='The user who created the order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('wallet', models.ForeignKey(help_text='The wallet related to the order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='homebroker.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='WalletAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last updated.', verbose_name='Updated at')),
                ('shares', models.IntegerField(default=0, help_text='The number of that asset shares there are in the wallet.', validators=[core.shared.field_validators.NonNegativeValueValidator()], verbose_name='Shares')),
                ('asset', models.ForeignKey(help_text='The asset of the wallet.', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='homebroker.asset', verbose_name='Asset')),
                ('wallet', models.ForeignKey(help_text='The wallet to which the asset belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='homebroker.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Wallet Asset',
                'verbose_name_plural': 'Wallet Assets',
            },
        ),
    ]
