# Generated by Django 5.1.6 on 2025-02-20 18:05

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last updated.', verbose_name='Updated at')),
                ('name', models.CharField(help_text='The name of the asset.', max_length=255, verbose_name='Name')),
                ('symbol', models.CharField(help_text='The symbol of the product', max_length=10, verbose_name='Symbol')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the asset. Must be greater than or equal to 0.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Price')),
                ('image', models.URLField(help_text='The image url of the asset.', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='AssetDaily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last updated.', verbose_name='Updated at')),
                ('date', models.DateTimeField(help_text='The date of the asset-daily.', verbose_name='Date')),
                ('asset', models.ForeignKey(help_text='The asset related to the asset-daily.', on_delete=django.db.models.deletion.CASCADE, related_name='asset_dailies', to='homebroker.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'AssetDaily',
                'verbose_name_plural': 'AssetDailies',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last updated.', verbose_name='Updated at')),
                ('shares', models.DecimalField(decimal_places=2, help_text='The number of shares related to the order.', max_digits=10, verbose_name='Shares')),
                ('partial', models.IntegerField(default=0, help_text='The number of shares already bought.', verbose_name='Partial')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the order.', max_digits=10, verbose_name='Price')),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('failed', 'Failed'), ('open', 'Open'), ('pending', 'Pending')], help_text='The status of the order.', max_length=10, verbose_name='Status')),
                ('type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], help_text='The type of the order.', max_length=10, verbose_name='Type')),
                ('asset', models.ForeignKey(help_text='The asset related to the order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='homebroker.asset', verbose_name='Asset')),
                ('user', models.ForeignKey(help_text='The user who created the order.', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last updated.', verbose_name='Updated at')),
                ('name', models.CharField(help_text='The name of the wallet.', max_length=255, verbose_name='Name')),
                ('user', models.ForeignKey(help_text='The user who created the wallet.', on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the record.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the record was created.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the record was last updated.', verbose_name='Updated at')),
                ('shares', models.DecimalField(decimal_places=2, help_text='The number of shares of the asset.', max_digits=10, verbose_name='Shares')),
                ('asset', models.ForeignKey(help_text='The asset of the wallet.', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='homebroker.asset', verbose_name='Asset')),
                ('wallet', models.ForeignKey(help_text='The wallet to which the asset belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='homebroker.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'WalletAsset',
                'verbose_name_plural': 'WalletAssets',
            },
        ),
    ]
