name: Backend Deploy

on:
  push:
    branches: [ main ]

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  qa:
    name: QA
    uses: ./.github/actions/ci.yaml

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: qa
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python 3.12
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: 3.12

  #   - name: Install dependencies
  #     run: |
  #       pip install poetry
  #       make install-dev

  #   - name: Deploy app
  #     run: make deploy
